[package]
name = "ckb-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
ckb-sdk = "4.1.0"
clap = { version = "4.5.46", features = ["derive"] }
cursive = "0.21.1"
log = "0.4.27"
rand = "0.9.2"
